### ISSUE TITLE
求助：安装不上去

### ISSUE THREAD

**Issue by shuaiyang2000** [TechDecryptor/pot-app-tts-plugin-microsoft#2]
插件版本：1.1.0[x86_64-pc-windows-msvc.zip]
显示已安装：
![1](https://github.com/TechDecryptor/pot-app-tts-plugin-microsoft/assets/56357218/0ec97ee5-1c00-4be5-a0c3-d44c2f9463a0)
但这里不显示：
![3](https://github.com/TechDecryptor/pot-app-tts-plugin-microsoft/assets/56357218/69e4a297-5e89-4e10-a516-3545d85fa381)
不知道是不是我参数填错了：
![2](https://github.com/TechDecryptor/pot-app-tts-plugin-microsoft/assets/56357218/206e78b4-6650-482d-abc5-0fe2555501c8)
翻译插件能安装使用：
![4](https://github.com/TechDecryptor/pot-app-tts-plugin-microsoft/assets/56357218/336795d6-10f0-4b8e-980b-4e5bd011fe46)

**Comment by TechDecryptor** [comment]
设置界面向下拉，有保存按钮
![image](https://github.com/TechDecryptor/pot-app-tts-plugin-microsoft/assets/145176897/cea8eb34-97c1-47b3-9a4d-f5c9a78b6384)
