### ISSUE TITLE
The rate limit has been reached

### ISSUE THREAD

**Issue by Lawrenauh** [TechDecryptor/pot-app-tts-plugin-microsoft#3]
1、挑选语音的时候多试了几次，然后就一直报错，重新安装无效：
{"ContentType":null,"SerializerSettings":null,"StatusCode":429,"Value":{"code":"TooManyRequests","details":null,"message":"The rate limit has been reached. The timeout in seconds can be found in the Retry-After header.","target":null,"innerError":null}}

2、能否提供自定义 key 接口？

**Comment by TechDecryptor** [comment]
1. 429等一会就好了，建议不要开代理，开启代理之后会比较频繁地触发。
2. 填写key这种，建议给pot提issue吧，pot内置比较好。
