### ISSUE TITLE
插件无法使用

### ISSUE THREAD

**Issue by awarson2233** [TechDecryptor/pot-app-tts-plugin-microsoft#4]
错误代码：{
"code": "InvalidRequest",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial",
"innerError": {
"code": "InvalidPayload",
"message": "Not supported TtsAudioFormat value audio-24khz-160kbitrate-mono-mp3 in AccFreeTrial"
}
}

**Comment by TechDecryptor** [comment]
我暂时也没有办法

**Comment by awarson2233** [comment]
行吧
