### ISSUE TITLE
”TooManyRequests“ Error

### ISSUE THREAD

**Issue by ElmTran** [TechDecryptor/pot-app-tts-plugin-microsoft#6]
环境：
win11 23H2
pot version 2.7.2
microsoft TTS plugin version 1.3.0
错误：
调用的时候出现了TooManyRequests错误，插件里面的homepage指向的地址404。
我的尝试：
我切换到了其他tts服务是正常的。初步估计是开发者的azure账号访问超出限制了。同时我对比了插件列表的地址，发现是pot-app-tts-plugin-microsoft和pot-app-translate-plugin-microsoft不一致。如果可以插件可以引入使用自己的azure key就好了。

**Comment by TechDecryptor** [comment]
这个插件使用的方法已经失效了，使用自己的azure key这种适合Pot软件内置，建议给Pot提交Issue，我这边没有Azure账号，也不打算做。
